// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: xrpc/internal/xrpcpb/xrpc.proto

package xrpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamSender int32

const (
	StreamSender_RPC_CLIENT StreamSender = 0
	StreamSender_RPC_SERVER StreamSender = 1
)

// Enum value maps for StreamSender.
var (
	StreamSender_name = map[int32]string{
		0: "RPC_CLIENT",
		1: "RPC_SERVER",
	}
	StreamSender_value = map[string]int32{
		"RPC_CLIENT": 0,
		"RPC_SERVER": 1,
	}
)

func (x StreamSender) Enum() *StreamSender {
	p := new(StreamSender)
	*p = x
	return p
}

func (x StreamSender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamSender) Descriptor() protoreflect.EnumDescriptor {
	return file_xrpc_internal_xrpcpb_xrpc_proto_enumTypes[0].Descriptor()
}

func (StreamSender) Type() protoreflect.EnumType {
	return &file_xrpc_internal_xrpcpb_xrpc_proto_enumTypes[0]
}

func (x StreamSender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamSender.Descriptor instead.
func (StreamSender) EnumDescriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{0}
}

type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to PacketType:
	//
	//	*Packet_System
	//	*Packet_Request
	//	*Packet_Response
	//	*Packet_StreamMsg
	PacketType    isPacket_PacketType `protobuf_oneof:"packet_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetPacketType() isPacket_PacketType {
	if x != nil {
		return x.PacketType
	}
	return nil
}

func (x *Packet) GetSystem() *System {
	if x != nil {
		if x, ok := x.PacketType.(*Packet_System); ok {
			return x.System
		}
	}
	return nil
}

func (x *Packet) GetRequest() *Request {
	if x != nil {
		if x, ok := x.PacketType.(*Packet_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Packet) GetResponse() *Response {
	if x != nil {
		if x, ok := x.PacketType.(*Packet_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Packet) GetStreamMsg() *StreamMsg {
	if x != nil {
		if x, ok := x.PacketType.(*Packet_StreamMsg); ok {
			return x.StreamMsg
		}
	}
	return nil
}

type isPacket_PacketType interface {
	isPacket_PacketType()
}

type Packet_System struct {
	System *System `protobuf:"bytes,1,opt,name=system,proto3,oneof"`
}

type Packet_Request struct {
	// Invokes
	Request *Request `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type Packet_Response struct {
	Response *Response `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

type Packet_StreamMsg struct {
	// Streams
	// StreamRequest stream_request = 4;
	// StreamResponse stream_response = 5;
	StreamMsg *StreamMsg `protobuf:"bytes,6,opt,name=stream_msg,json=streamMsg,proto3,oneof"`
}

func (*Packet_System) isPacket_PacketType() {}

func (*Packet_Request) isPacket_PacketType() {}

func (*Packet_Response) isPacket_PacketType() {}

func (*Packet_StreamMsg) isPacket_PacketType() {}

type System struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SystemType:
	//
	//	*System_Hello
	//	*System_CtxCancel
	//	*System_SetWindow
	SystemType    isSystem_SystemType `protobuf_oneof:"system_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *System) Reset() {
	*x = System{}
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *System) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*System) ProtoMessage() {}

func (x *System) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use System.ProtoReflect.Descriptor instead.
func (*System) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{1}
}

func (x *System) GetSystemType() isSystem_SystemType {
	if x != nil {
		return x.SystemType
	}
	return nil
}

func (x *System) GetHello() *Hello {
	if x != nil {
		if x, ok := x.SystemType.(*System_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *System) GetCtxCancel() *CtxCancel {
	if x != nil {
		if x, ok := x.SystemType.(*System_CtxCancel); ok {
			return x.CtxCancel
		}
	}
	return nil
}

func (x *System) GetSetWindow() uint64 {
	if x != nil {
		if x, ok := x.SystemType.(*System_SetWindow); ok {
			return x.SetWindow
		}
	}
	return 0
}

type isSystem_SystemType interface {
	isSystem_SystemType()
}

type System_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type System_CtxCancel struct {
	CtxCancel *CtxCancel `protobuf:"bytes,2,opt,name=ctx_cancel,json=ctxCancel,proto3,oneof"`
}

type System_SetWindow struct {
	SetWindow uint64 `protobuf:"varint,3,opt,name=set_window,json=setWindow,proto3,oneof"`
}

func (*System_Hello) isSystem_SystemType() {}

func (*System_CtxCancel) isSystem_SystemType() {}

func (*System_SetWindow) isSystem_SystemType() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowControl   bool                   `protobuf:"varint,1,opt,name=flow_control,json=flowControl,proto3" json:"flow_control,omitempty"`
	InitialWindow uint64                 `protobuf:"varint,2,opt,name=initial_window,json=initialWindow,proto3" json:"initial_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetFlowControl() bool {
	if x != nil {
		return x.FlowControl
	}
	return false
}

func (x *Hello) GetInitialWindow() uint64 {
	if x != nil {
		return x.InitialWindow
	}
	return 0
}

type CtxCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cause         string                 `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"` // TODO: error struct using anypb
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtxCancel) Reset() {
	*x = CtxCancel{}
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtxCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtxCancel) ProtoMessage() {}

func (x *CtxCancel) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtxCancel.ProtoReflect.Descriptor instead.
func (*CtxCancel) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{3}
}

func (x *CtxCancel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CtxCancel) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*Metadata_Pair       `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{4}
}

func (x *Metadata) GetPairs() []*Metadata_Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// type = 2;
	Service        string     `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Method         string     `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	IsNotification bool       `protobuf:"varint,5,opt,name=is_notification,json=isNotification,proto3" json:"is_notification,omitempty"`
	Metadata       *Metadata  `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	In             *anypb.Any `protobuf:"bytes,7,opt,name=in,proto3" json:"in,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{5}
}

func (x *Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetIsNotification() bool {
	if x != nil {
		return x.IsNotification
	}
	return false
}

func (x *Request) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Request) GetIn() *anypb.Any {
	if x != nil {
		return x.In
	}
	return nil
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// type = 2;
	Metadata      *Metadata  `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Response      *anypb.Any `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	ErrorNum      int32      `protobuf:"varint,5,opt,name=error_num,json=errorNum,proto3" json:"error_num,omitempty"`
	Error         string     `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Response) GetResponse() *anypb.Any {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Response) GetErrorNum() int32 {
	if x != nil {
		return x.ErrorNum
	}
	return 0
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Service       string `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Method        string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	InitialWindow uint64 `protobuf:"varint,5,opt,name=initial_window,json=initialWindow,proto3" json:"initial_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{7}
}

func (x *StreamRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StreamRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *StreamRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *StreamRequest) GetInitialWindow() uint64 {
	if x != nil {
		return x.InitialWindow
	}
	return 0
}

type StreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InitialWindow uint64 `protobuf:"varint,3,opt,name=initial_window,json=initialWindow,proto3" json:"initial_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{8}
}

func (x *StreamResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StreamResponse) GetInitialWindow() uint64 {
	if x != nil {
		return x.InitialWindow
	}
	return 0
}

type StreamClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorNum      int32                  `protobuf:"varint,1,opt,name=error_num,json=errorNum,proto3" json:"error_num,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamClose) Reset() {
	*x = StreamClose{}
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamClose) ProtoMessage() {}

func (x *StreamClose) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamClose.ProtoReflect.Descriptor instead.
func (*StreamClose) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{9}
}

func (x *StreamClose) GetErrorNum() int32 {
	if x != nil {
		return x.ErrorNum
	}
	return 0
}

func (x *StreamClose) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamMsg struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StreamId uint64                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Sender   StreamSender           `protobuf:"varint,2,opt,name=sender,proto3,enum=xrpcpb.StreamSender" json:"sender,omitempty"`
	SeqId    uint64                 `protobuf:"varint,3,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	// Types that are valid to be assigned to MsgType:
	//
	//	*StreamMsg_SetWindow
	//	*StreamMsg_Msg
	//	*StreamMsg_Close
	MsgType       isStreamMsg_MsgType `protobuf_oneof:"msg_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMsg) Reset() {
	*x = StreamMsg{}
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMsg) ProtoMessage() {}

func (x *StreamMsg) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMsg.ProtoReflect.Descriptor instead.
func (*StreamMsg) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{10}
}

func (x *StreamMsg) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *StreamMsg) GetSender() StreamSender {
	if x != nil {
		return x.Sender
	}
	return StreamSender_RPC_CLIENT
}

func (x *StreamMsg) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *StreamMsg) GetMsgType() isStreamMsg_MsgType {
	if x != nil {
		return x.MsgType
	}
	return nil
}

func (x *StreamMsg) GetSetWindow() uint64 {
	if x != nil {
		if x, ok := x.MsgType.(*StreamMsg_SetWindow); ok {
			return x.SetWindow
		}
	}
	return 0
}

func (x *StreamMsg) GetMsg() *anypb.Any {
	if x != nil {
		if x, ok := x.MsgType.(*StreamMsg_Msg); ok {
			return x.Msg
		}
	}
	return nil
}

func (x *StreamMsg) GetClose() *StreamClose {
	if x != nil {
		if x, ok := x.MsgType.(*StreamMsg_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isStreamMsg_MsgType interface {
	isStreamMsg_MsgType()
}

type StreamMsg_SetWindow struct {
	SetWindow uint64 `protobuf:"varint,4,opt,name=set_window,json=setWindow,proto3,oneof"`
}

type StreamMsg_Msg struct {
	Msg *anypb.Any `protobuf:"bytes,5,opt,name=msg,proto3,oneof"`
}

type StreamMsg_Close struct {
	Close *StreamClose `protobuf:"bytes,6,opt,name=close,proto3,oneof"`
}

func (*StreamMsg_SetWindow) isStreamMsg_MsgType() {}

func (*StreamMsg_Msg) isStreamMsg_MsgType() {}

func (*StreamMsg_Close) isStreamMsg_MsgType() {}

type Metadata_Pair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata_Pair) Reset() {
	*x = Metadata_Pair{}
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata_Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata_Pair) ProtoMessage() {}

func (x *Metadata_Pair) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata_Pair.ProtoReflect.Descriptor instead.
func (*Metadata_Pair) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Metadata_Pair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Metadata_Pair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_xrpc_internal_xrpcpb_xrpc_proto protoreflect.FileDescriptor

const file_xrpc_internal_xrpcpb_xrpc_proto_rawDesc = "" +
	"\n" +
	"\x1fxrpc/internal/xrpcpb/xrpc.proto\x12\x06xrpcpb\x1a\x19google/protobuf/any.proto\"\xd2\x01\n" +
	"\x06Packet\x12(\n" +
	"\x06system\x18\x01 \x01(\v2\x0e.xrpcpb.SystemH\x00R\x06system\x12+\n" +
	"\arequest\x18\x02 \x01(\v2\x0f.xrpcpb.RequestH\x00R\arequest\x12.\n" +
	"\bresponse\x18\x03 \x01(\v2\x10.xrpcpb.ResponseH\x00R\bresponse\x122\n" +
	"\n" +
	"stream_msg\x18\x06 \x01(\v2\x11.xrpcpb.StreamMsgH\x00R\tstreamMsgB\r\n" +
	"\vpacket_type\"\x93\x01\n" +
	"\x06System\x12%\n" +
	"\x05hello\x18\x01 \x01(\v2\r.xrpcpb.HelloH\x00R\x05hello\x122\n" +
	"\n" +
	"ctx_cancel\x18\x02 \x01(\v2\x11.xrpcpb.CtxCancelH\x00R\tctxCancel\x12\x1f\n" +
	"\n" +
	"set_window\x18\x03 \x01(\x04H\x00R\tsetWindowB\r\n" +
	"\vsystem_type\"Q\n" +
	"\x05Hello\x12!\n" +
	"\fflow_control\x18\x01 \x01(\bR\vflowControl\x12%\n" +
	"\x0einitial_window\x18\x02 \x01(\x04R\rinitialWindow\"1\n" +
	"\tCtxCancel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05cause\x18\x02 \x01(\tR\x05cause\"g\n" +
	"\bMetadata\x12+\n" +
	"\x05pairs\x18\x01 \x03(\v2\x15.xrpcpb.Metadata.PairR\x05pairs\x1a.\n" +
	"\x04Pair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc8\x01\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12'\n" +
	"\x0fis_notification\x18\x05 \x01(\bR\x0eisNotification\x12,\n" +
	"\bmetadata\x18\x06 \x01(\v2\x10.xrpcpb.MetadataR\bmetadata\x12$\n" +
	"\x02in\x18\a \x01(\v2\x14.google.protobuf.AnyR\x02in\"\xad\x01\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12,\n" +
	"\bmetadata\x18\x03 \x01(\v2\x10.xrpcpb.MetadataR\bmetadata\x120\n" +
	"\bresponse\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\bresponse\x12\x1b\n" +
	"\terror_num\x18\x05 \x01(\x05R\berrorNum\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"x\n" +
	"\rStreamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12%\n" +
	"\x0einitial_window\x18\x05 \x01(\x04R\rinitialWindow\"G\n" +
	"\x0eStreamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12%\n" +
	"\x0einitial_window\x18\x03 \x01(\x04R\rinitialWindow\"@\n" +
	"\vStreamClose\x12\x1b\n" +
	"\terror_num\x18\x01 \x01(\x05R\berrorNum\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xf1\x01\n" +
	"\tStreamMsg\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamId\x12,\n" +
	"\x06sender\x18\x02 \x01(\x0e2\x14.xrpcpb.StreamSenderR\x06sender\x12\x15\n" +
	"\x06seq_id\x18\x03 \x01(\x04R\x05seqId\x12\x1f\n" +
	"\n" +
	"set_window\x18\x04 \x01(\x04H\x00R\tsetWindow\x12(\n" +
	"\x03msg\x18\x05 \x01(\v2\x14.google.protobuf.AnyH\x00R\x03msg\x12+\n" +
	"\x05close\x18\x06 \x01(\v2\x13.xrpcpb.StreamCloseH\x00R\x05closeB\n" +
	"\n" +
	"\bmsg_type*.\n" +
	"\fStreamSender\x12\x0e\n" +
	"\n" +
	"RPC_CLIENT\x10\x00\x12\x0e\n" +
	"\n" +
	"RPC_SERVER\x10\x01B\x1eZ\x1cgo-xrpc/xrpc/internal/xrpcpbb\x06proto3"

var (
	file_xrpc_internal_xrpcpb_xrpc_proto_rawDescOnce sync.Once
	file_xrpc_internal_xrpcpb_xrpc_proto_rawDescData []byte
)

func file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP() []byte {
	file_xrpc_internal_xrpcpb_xrpc_proto_rawDescOnce.Do(func() {
		file_xrpc_internal_xrpcpb_xrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xrpc_internal_xrpcpb_xrpc_proto_rawDesc), len(file_xrpc_internal_xrpcpb_xrpc_proto_rawDesc)))
	})
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescData
}

var file_xrpc_internal_xrpcpb_xrpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_xrpc_internal_xrpcpb_xrpc_proto_goTypes = []any{
	(StreamSender)(0),      // 0: xrpcpb.StreamSender
	(*Packet)(nil),         // 1: xrpcpb.Packet
	(*System)(nil),         // 2: xrpcpb.System
	(*Hello)(nil),          // 3: xrpcpb.Hello
	(*CtxCancel)(nil),      // 4: xrpcpb.CtxCancel
	(*Metadata)(nil),       // 5: xrpcpb.Metadata
	(*Request)(nil),        // 6: xrpcpb.Request
	(*Response)(nil),       // 7: xrpcpb.Response
	(*StreamRequest)(nil),  // 8: xrpcpb.StreamRequest
	(*StreamResponse)(nil), // 9: xrpcpb.StreamResponse
	(*StreamClose)(nil),    // 10: xrpcpb.StreamClose
	(*StreamMsg)(nil),      // 11: xrpcpb.StreamMsg
	(*Metadata_Pair)(nil),  // 12: xrpcpb.Metadata.Pair
	(*anypb.Any)(nil),      // 13: google.protobuf.Any
}
var file_xrpc_internal_xrpcpb_xrpc_proto_depIdxs = []int32{
	2,  // 0: xrpcpb.Packet.system:type_name -> xrpcpb.System
	6,  // 1: xrpcpb.Packet.request:type_name -> xrpcpb.Request
	7,  // 2: xrpcpb.Packet.response:type_name -> xrpcpb.Response
	11, // 3: xrpcpb.Packet.stream_msg:type_name -> xrpcpb.StreamMsg
	3,  // 4: xrpcpb.System.hello:type_name -> xrpcpb.Hello
	4,  // 5: xrpcpb.System.ctx_cancel:type_name -> xrpcpb.CtxCancel
	12, // 6: xrpcpb.Metadata.pairs:type_name -> xrpcpb.Metadata.Pair
	5,  // 7: xrpcpb.Request.metadata:type_name -> xrpcpb.Metadata
	13, // 8: xrpcpb.Request.in:type_name -> google.protobuf.Any
	5,  // 9: xrpcpb.Response.metadata:type_name -> xrpcpb.Metadata
	13, // 10: xrpcpb.Response.response:type_name -> google.protobuf.Any
	0,  // 11: xrpcpb.StreamMsg.sender:type_name -> xrpcpb.StreamSender
	13, // 12: xrpcpb.StreamMsg.msg:type_name -> google.protobuf.Any
	10, // 13: xrpcpb.StreamMsg.close:type_name -> xrpcpb.StreamClose
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_xrpc_internal_xrpcpb_xrpc_proto_init() }
func file_xrpc_internal_xrpcpb_xrpc_proto_init() {
	if File_xrpc_internal_xrpcpb_xrpc_proto != nil {
		return
	}
	file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[0].OneofWrappers = []any{
		(*Packet_System)(nil),
		(*Packet_Request)(nil),
		(*Packet_Response)(nil),
		(*Packet_StreamMsg)(nil),
	}
	file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[1].OneofWrappers = []any{
		(*System_Hello)(nil),
		(*System_CtxCancel)(nil),
		(*System_SetWindow)(nil),
	}
	file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[10].OneofWrappers = []any{
		(*StreamMsg_SetWindow)(nil),
		(*StreamMsg_Msg)(nil),
		(*StreamMsg_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xrpc_internal_xrpcpb_xrpc_proto_rawDesc), len(file_xrpc_internal_xrpcpb_xrpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xrpc_internal_xrpcpb_xrpc_proto_goTypes,
		DependencyIndexes: file_xrpc_internal_xrpcpb_xrpc_proto_depIdxs,
		EnumInfos:         file_xrpc_internal_xrpcpb_xrpc_proto_enumTypes,
		MessageInfos:      file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes,
	}.Build()
	File_xrpc_internal_xrpcpb_xrpc_proto = out.File
	file_xrpc_internal_xrpcpb_xrpc_proto_goTypes = nil
	file_xrpc_internal_xrpcpb_xrpc_proto_depIdxs = nil
}
