// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.4
// source: xrpc/internal/xrpcpb/xrpc.proto

package xrpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamSender int32

const (
	StreamSender_RPC_CLIENT StreamSender = 0
	StreamSender_RPC_SERVER StreamSender = 1
)

// Enum value maps for StreamSender.
var (
	StreamSender_name = map[int32]string{
		0: "RPC_CLIENT",
		1: "RPC_SERVER",
	}
	StreamSender_value = map[string]int32{
		"RPC_CLIENT": 0,
		"RPC_SERVER": 1,
	}
)

func (x StreamSender) Enum() *StreamSender {
	p := new(StreamSender)
	*p = x
	return p
}

func (x StreamSender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamSender) Descriptor() protoreflect.EnumDescriptor {
	return file_xrpc_internal_xrpcpb_xrpc_proto_enumTypes[0].Descriptor()
}

func (StreamSender) Type() protoreflect.EnumType {
	return &file_xrpc_internal_xrpcpb_xrpc_proto_enumTypes[0]
}

func (x StreamSender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamSender.Descriptor instead.
func (StreamSender) EnumDescriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{0}
}

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to PacketType:
	//
	//	*Packet_System
	//	*Packet_Request
	//	*Packet_Response
	//	*Packet_StreamMsg
	PacketType isPacket_PacketType `protobuf_oneof:"packet_type"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{0}
}

func (m *Packet) GetPacketType() isPacket_PacketType {
	if m != nil {
		return m.PacketType
	}
	return nil
}

func (x *Packet) GetSystem() *System {
	if x, ok := x.GetPacketType().(*Packet_System); ok {
		return x.System
	}
	return nil
}

func (x *Packet) GetRequest() *Request {
	if x, ok := x.GetPacketType().(*Packet_Request); ok {
		return x.Request
	}
	return nil
}

func (x *Packet) GetResponse() *Response {
	if x, ok := x.GetPacketType().(*Packet_Response); ok {
		return x.Response
	}
	return nil
}

func (x *Packet) GetStreamMsg() *StreamMsg {
	if x, ok := x.GetPacketType().(*Packet_StreamMsg); ok {
		return x.StreamMsg
	}
	return nil
}

type isPacket_PacketType interface {
	isPacket_PacketType()
}

type Packet_System struct {
	System *System `protobuf:"bytes,1,opt,name=system,proto3,oneof"`
}

type Packet_Request struct {
	// Invokes
	Request *Request `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type Packet_Response struct {
	Response *Response `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

type Packet_StreamMsg struct {
	// Streams
	// StreamRequest stream_request = 4;
	// StreamResponse stream_response = 5;
	StreamMsg *StreamMsg `protobuf:"bytes,6,opt,name=stream_msg,json=streamMsg,proto3,oneof"`
}

func (*Packet_System) isPacket_PacketType() {}

func (*Packet_Request) isPacket_PacketType() {}

func (*Packet_Response) isPacket_PacketType() {}

func (*Packet_StreamMsg) isPacket_PacketType() {}

type System struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to SystemType:
	//
	//	*System_Hello
	//	*System_CtxCancel
	//	*System_SetWindow
	SystemType isSystem_SystemType `protobuf_oneof:"system_type"`
}

func (x *System) Reset() {
	*x = System{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *System) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*System) ProtoMessage() {}

func (x *System) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use System.ProtoReflect.Descriptor instead.
func (*System) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{1}
}

func (m *System) GetSystemType() isSystem_SystemType {
	if m != nil {
		return m.SystemType
	}
	return nil
}

func (x *System) GetHello() *Hello {
	if x, ok := x.GetSystemType().(*System_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *System) GetCtxCancel() *CtxCancel {
	if x, ok := x.GetSystemType().(*System_CtxCancel); ok {
		return x.CtxCancel
	}
	return nil
}

func (x *System) GetSetWindow() uint64 {
	if x, ok := x.GetSystemType().(*System_SetWindow); ok {
		return x.SetWindow
	}
	return 0
}

type isSystem_SystemType interface {
	isSystem_SystemType()
}

type System_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type System_CtxCancel struct {
	CtxCancel *CtxCancel `protobuf:"bytes,2,opt,name=ctx_cancel,json=ctxCancel,proto3,oneof"`
}

type System_SetWindow struct {
	SetWindow uint64 `protobuf:"varint,3,opt,name=set_window,json=setWindow,proto3,oneof"`
}

func (*System_Hello) isSystem_SystemType() {}

func (*System_CtxCancel) isSystem_SystemType() {}

func (*System_SetWindow) isSystem_SystemType() {}

type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlowControl   bool   `protobuf:"varint,1,opt,name=flow_control,json=flowControl,proto3" json:"flow_control,omitempty"`
	InitialWindow uint64 `protobuf:"varint,2,opt,name=initial_window,json=initialWindow,proto3" json:"initial_window,omitempty"`
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetFlowControl() bool {
	if x != nil {
		return x.FlowControl
	}
	return false
}

func (x *Hello) GetInitialWindow() uint64 {
	if x != nil {
		return x.InitialWindow
	}
	return 0
}

type CtxCancel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cause string `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"` // TODO: error struct using anypb
}

func (x *CtxCancel) Reset() {
	*x = CtxCancel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CtxCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtxCancel) ProtoMessage() {}

func (x *CtxCancel) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtxCancel.ProtoReflect.Descriptor instead.
func (*CtxCancel) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{3}
}

func (x *CtxCancel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CtxCancel) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs []*Metadata_Pair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{4}
}

func (x *Metadata) GetPairs() []*Metadata_Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// type = 2;
	Service        string     `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Method         string     `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	IsNotification bool       `protobuf:"varint,5,opt,name=is_notification,json=isNotification,proto3" json:"is_notification,omitempty"`
	Metadata       *Metadata  `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	In             *anypb.Any `protobuf:"bytes,7,opt,name=in,proto3" json:"in,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{5}
}

func (x *Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetIsNotification() bool {
	if x != nil {
		return x.IsNotification
	}
	return false
}

func (x *Request) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Request) GetIn() *anypb.Any {
	if x != nil {
		return x.In
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// type = 2;
	Metadata *Metadata  `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Response *anypb.Any `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	ErrorNum int32      `protobuf:"varint,5,opt,name=error_num,json=errorNum,proto3" json:"error_num,omitempty"`
	Error    string     `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Response) GetResponse() *anypb.Any {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Response) GetErrorNum() int32 {
	if x != nil {
		return x.ErrorNum
	}
	return 0
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Service       string `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Method        string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	InitialWindow uint64 `protobuf:"varint,5,opt,name=initial_window,json=initialWindow,proto3" json:"initial_window,omitempty"`
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{7}
}

func (x *StreamRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StreamRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *StreamRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *StreamRequest) GetInitialWindow() uint64 {
	if x != nil {
		return x.InitialWindow
	}
	return 0
}

type StreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InitialWindow uint64 `protobuf:"varint,3,opt,name=initial_window,json=initialWindow,proto3" json:"initial_window,omitempty"`
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{8}
}

func (x *StreamResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StreamResponse) GetInitialWindow() uint64 {
	if x != nil {
		return x.InitialWindow
	}
	return 0
}

type StreamClose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorNum int32  `protobuf:"varint,1,opt,name=error_num,json=errorNum,proto3" json:"error_num,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *StreamClose) Reset() {
	*x = StreamClose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamClose) ProtoMessage() {}

func (x *StreamClose) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamClose.ProtoReflect.Descriptor instead.
func (*StreamClose) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{9}
}

func (x *StreamClose) GetErrorNum() int32 {
	if x != nil {
		return x.ErrorNum
	}
	return 0
}

func (x *StreamClose) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender StreamSender `protobuf:"varint,2,opt,name=sender,proto3,enum=xrpcpb.StreamSender" json:"sender,omitempty"`
	// Types that are assignable to MsgType:
	//
	//	*StreamMsg_SetWindow
	//	*StreamMsg_Msg
	//	*StreamMsg_Close
	MsgType isStreamMsg_MsgType `protobuf_oneof:"msg_type"`
}

func (x *StreamMsg) Reset() {
	*x = StreamMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMsg) ProtoMessage() {}

func (x *StreamMsg) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMsg.ProtoReflect.Descriptor instead.
func (*StreamMsg) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{10}
}

func (x *StreamMsg) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StreamMsg) GetSender() StreamSender {
	if x != nil {
		return x.Sender
	}
	return StreamSender_RPC_CLIENT
}

func (m *StreamMsg) GetMsgType() isStreamMsg_MsgType {
	if m != nil {
		return m.MsgType
	}
	return nil
}

func (x *StreamMsg) GetSetWindow() uint64 {
	if x, ok := x.GetMsgType().(*StreamMsg_SetWindow); ok {
		return x.SetWindow
	}
	return 0
}

func (x *StreamMsg) GetMsg() *anypb.Any {
	if x, ok := x.GetMsgType().(*StreamMsg_Msg); ok {
		return x.Msg
	}
	return nil
}

func (x *StreamMsg) GetClose() *StreamClose {
	if x, ok := x.GetMsgType().(*StreamMsg_Close); ok {
		return x.Close
	}
	return nil
}

type isStreamMsg_MsgType interface {
	isStreamMsg_MsgType()
}

type StreamMsg_SetWindow struct {
	SetWindow uint64 `protobuf:"varint,3,opt,name=set_window,json=setWindow,proto3,oneof"`
}

type StreamMsg_Msg struct {
	Msg *anypb.Any `protobuf:"bytes,4,opt,name=msg,proto3,oneof"`
}

type StreamMsg_Close struct {
	Close *StreamClose `protobuf:"bytes,5,opt,name=close,proto3,oneof"`
}

func (*StreamMsg_SetWindow) isStreamMsg_MsgType() {}

func (*StreamMsg_Msg) isStreamMsg_MsgType() {}

func (*StreamMsg_Close) isStreamMsg_MsgType() {}

type Metadata_Pair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Metadata_Pair) Reset() {
	*x = Metadata_Pair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata_Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata_Pair) ProtoMessage() {}

func (x *Metadata_Pair) ProtoReflect() protoreflect.Message {
	mi := &file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata_Pair.ProtoReflect.Descriptor instead.
func (*Metadata_Pair) Descriptor() ([]byte, []int) {
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Metadata_Pair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Metadata_Pair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_xrpc_internal_xrpcpb_xrpc_proto protoreflect.FileDescriptor

var file_xrpc_internal_xrpcpb_xrpc_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x78, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x78, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2f, 0x78, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x78, 0x72, 0x70, 0x63, 0x70, 0x62, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd2, 0x01, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x28, 0x0a, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x78, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x48,
	0x00, 0x52, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x78, 0x72, 0x70,
	0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x78, 0x72, 0x70, 0x63, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x5f, 0x6d, 0x73, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x78, 0x72, 0x70,
	0x63, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52,
	0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x73, 0x67, 0x42, 0x0d, 0x0a, 0x0b, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x06, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x12, 0x25, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x78, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x32, 0x0a, 0x0a, 0x63,
	0x74, 0x78, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x78, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x43, 0x74, 0x78, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x48, 0x00, 0x52, 0x09, 0x63, 0x74, 0x78, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x12,
	0x1f, 0x0a, 0x0a, 0x73, 0x65, 0x74, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x09, 0x73, 0x65, 0x74, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77,
	0x42, 0x0d, 0x0a, 0x0b, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x51, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x6c, 0x6f, 0x77,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b,
	0x66, 0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x57, 0x69, 0x6e, 0x64,
	0x6f, 0x77, 0x22, 0x31, 0x0a, 0x09, 0x43, 0x74, 0x78, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x63, 0x61, 0x75, 0x73, 0x65, 0x22, 0x67, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x78, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x1a, 0x2e,
	0x0a, 0x04, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xc8,
	0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x27, 0x0a, 0x0f,
	0x69, 0x73, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x78, 0x72, 0x70, 0x63, 0x70, 0x62,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x02, 0x69, 0x6e, 0x22, 0xad, 0x01, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x78, 0x72, 0x70, 0x63, 0x70,
	0x62, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x30, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f,
	0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x78, 0x0a, 0x0d, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x25, 0x0a, 0x0e,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x57, 0x69, 0x6e,
	0x64, 0x6f, 0x77, 0x22, 0x47, 0x0a, 0x0e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c,
	0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x22, 0x40, 0x0a, 0x0b,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xcd,
	0x01, 0x0a, 0x09, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x78,
	0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0a, 0x73, 0x65,
	0x74, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00,
	0x52, 0x09, 0x73, 0x65, 0x74, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x12, 0x28, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x48, 0x00,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2b, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x78, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6c, 0x6f,
	0x73, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x2e,
	0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x0a, 0x52, 0x50, 0x43, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x52, 0x50, 0x43, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x01, 0x42, 0x1e,
	0x5a, 0x1c, 0x67, 0x6f, 0x2d, 0x78, 0x72, 0x70, 0x63, 0x2f, 0x78, 0x72, 0x70, 0x63, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x78, 0x72, 0x70, 0x63, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xrpc_internal_xrpcpb_xrpc_proto_rawDescOnce sync.Once
	file_xrpc_internal_xrpcpb_xrpc_proto_rawDescData = file_xrpc_internal_xrpcpb_xrpc_proto_rawDesc
)

func file_xrpc_internal_xrpcpb_xrpc_proto_rawDescGZIP() []byte {
	file_xrpc_internal_xrpcpb_xrpc_proto_rawDescOnce.Do(func() {
		file_xrpc_internal_xrpcpb_xrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_xrpc_internal_xrpcpb_xrpc_proto_rawDescData)
	})
	return file_xrpc_internal_xrpcpb_xrpc_proto_rawDescData
}

var file_xrpc_internal_xrpcpb_xrpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_xrpc_internal_xrpcpb_xrpc_proto_goTypes = []interface{}{
	(StreamSender)(0),      // 0: xrpcpb.StreamSender
	(*Packet)(nil),         // 1: xrpcpb.Packet
	(*System)(nil),         // 2: xrpcpb.System
	(*Hello)(nil),          // 3: xrpcpb.Hello
	(*CtxCancel)(nil),      // 4: xrpcpb.CtxCancel
	(*Metadata)(nil),       // 5: xrpcpb.Metadata
	(*Request)(nil),        // 6: xrpcpb.Request
	(*Response)(nil),       // 7: xrpcpb.Response
	(*StreamRequest)(nil),  // 8: xrpcpb.StreamRequest
	(*StreamResponse)(nil), // 9: xrpcpb.StreamResponse
	(*StreamClose)(nil),    // 10: xrpcpb.StreamClose
	(*StreamMsg)(nil),      // 11: xrpcpb.StreamMsg
	(*Metadata_Pair)(nil),  // 12: xrpcpb.Metadata.Pair
	(*anypb.Any)(nil),      // 13: google.protobuf.Any
}
var file_xrpc_internal_xrpcpb_xrpc_proto_depIdxs = []int32{
	2,  // 0: xrpcpb.Packet.system:type_name -> xrpcpb.System
	6,  // 1: xrpcpb.Packet.request:type_name -> xrpcpb.Request
	7,  // 2: xrpcpb.Packet.response:type_name -> xrpcpb.Response
	11, // 3: xrpcpb.Packet.stream_msg:type_name -> xrpcpb.StreamMsg
	3,  // 4: xrpcpb.System.hello:type_name -> xrpcpb.Hello
	4,  // 5: xrpcpb.System.ctx_cancel:type_name -> xrpcpb.CtxCancel
	12, // 6: xrpcpb.Metadata.pairs:type_name -> xrpcpb.Metadata.Pair
	5,  // 7: xrpcpb.Request.metadata:type_name -> xrpcpb.Metadata
	13, // 8: xrpcpb.Request.in:type_name -> google.protobuf.Any
	5,  // 9: xrpcpb.Response.metadata:type_name -> xrpcpb.Metadata
	13, // 10: xrpcpb.Response.response:type_name -> google.protobuf.Any
	0,  // 11: xrpcpb.StreamMsg.sender:type_name -> xrpcpb.StreamSender
	13, // 12: xrpcpb.StreamMsg.msg:type_name -> google.protobuf.Any
	10, // 13: xrpcpb.StreamMsg.close:type_name -> xrpcpb.StreamClose
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_xrpc_internal_xrpcpb_xrpc_proto_init() }
func file_xrpc_internal_xrpcpb_xrpc_proto_init() {
	if File_xrpc_internal_xrpcpb_xrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*System); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CtxCancel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamClose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata_Pair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Packet_System)(nil),
		(*Packet_Request)(nil),
		(*Packet_Response)(nil),
		(*Packet_StreamMsg)(nil),
	}
	file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*System_Hello)(nil),
		(*System_CtxCancel)(nil),
		(*System_SetWindow)(nil),
	}
	file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*StreamMsg_SetWindow)(nil),
		(*StreamMsg_Msg)(nil),
		(*StreamMsg_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xrpc_internal_xrpcpb_xrpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xrpc_internal_xrpcpb_xrpc_proto_goTypes,
		DependencyIndexes: file_xrpc_internal_xrpcpb_xrpc_proto_depIdxs,
		EnumInfos:         file_xrpc_internal_xrpcpb_xrpc_proto_enumTypes,
		MessageInfos:      file_xrpc_internal_xrpcpb_xrpc_proto_msgTypes,
	}.Build()
	File_xrpc_internal_xrpcpb_xrpc_proto = out.File
	file_xrpc_internal_xrpcpb_xrpc_proto_rawDesc = nil
	file_xrpc_internal_xrpcpb_xrpc_proto_goTypes = nil
	file_xrpc_internal_xrpcpb_xrpc_proto_depIdxs = nil
}
