// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: proto/api.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PingReplyer_Ping_FullMethodName            = "/proto.PingReplyer/Ping"
	PingReplyer_StreamPingsBoth_FullMethodName = "/proto.PingReplyer/StreamPingsBoth"
	PingReplyer_StreamPingsIn_FullMethodName   = "/proto.PingReplyer/StreamPingsIn"
	PingReplyer_StreamPingsOut_FullMethodName  = "/proto.PingReplyer/StreamPingsOut"
)

// PingReplyerClient is the client API for PingReplyer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingReplyerClient interface {
	Ping(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error)
	StreamPingsBoth(ctx context.Context, opts ...grpc.CallOption) (PingReplyer_StreamPingsBothClient, error)
	StreamPingsIn(ctx context.Context, opts ...grpc.CallOption) (PingReplyer_StreamPingsInClient, error)
	StreamPingsOut(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (PingReplyer_StreamPingsOutClient, error)
}

type pingReplyerClient struct {
	cc grpc.ClientConnInterface
}

func NewPingReplyerClient(cc grpc.ClientConnInterface) PingReplyerClient {
	return &pingReplyerClient{cc}
}

func (c *pingReplyerClient) Ping(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error) {
	out := new(PingMessage)
	err := c.cc.Invoke(ctx, PingReplyer_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingReplyerClient) StreamPingsBoth(ctx context.Context, opts ...grpc.CallOption) (PingReplyer_StreamPingsBothClient, error) {
	stream, err := c.cc.NewStream(ctx, &PingReplyer_ServiceDesc.Streams[0], PingReplyer_StreamPingsBoth_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &pingReplyerStreamPingsBothClient{stream}
	return x, nil
}

type PingReplyer_StreamPingsBothClient interface {
	Send(*PingMessage) error
	Recv() (*PingMessage, error)
	grpc.ClientStream
}

type pingReplyerStreamPingsBothClient struct {
	grpc.ClientStream
}

func (x *pingReplyerStreamPingsBothClient) Send(m *PingMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pingReplyerStreamPingsBothClient) Recv() (*PingMessage, error) {
	m := new(PingMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pingReplyerClient) StreamPingsIn(ctx context.Context, opts ...grpc.CallOption) (PingReplyer_StreamPingsInClient, error) {
	stream, err := c.cc.NewStream(ctx, &PingReplyer_ServiceDesc.Streams[1], PingReplyer_StreamPingsIn_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &pingReplyerStreamPingsInClient{stream}
	return x, nil
}

type PingReplyer_StreamPingsInClient interface {
	Send(*PingMessage) error
	CloseAndRecv() (*PingMessage, error)
	grpc.ClientStream
}

type pingReplyerStreamPingsInClient struct {
	grpc.ClientStream
}

func (x *pingReplyerStreamPingsInClient) Send(m *PingMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pingReplyerStreamPingsInClient) CloseAndRecv() (*PingMessage, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PingMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pingReplyerClient) StreamPingsOut(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (PingReplyer_StreamPingsOutClient, error) {
	stream, err := c.cc.NewStream(ctx, &PingReplyer_ServiceDesc.Streams[2], PingReplyer_StreamPingsOut_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &pingReplyerStreamPingsOutClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PingReplyer_StreamPingsOutClient interface {
	Recv() (*PingMessage, error)
	grpc.ClientStream
}

type pingReplyerStreamPingsOutClient struct {
	grpc.ClientStream
}

func (x *pingReplyerStreamPingsOutClient) Recv() (*PingMessage, error) {
	m := new(PingMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PingReplyerServer is the server API for PingReplyer service.
// All implementations must embed UnimplementedPingReplyerServer
// for forward compatibility
type PingReplyerServer interface {
	Ping(context.Context, *PingMessage) (*PingMessage, error)
	StreamPingsBoth(PingReplyer_StreamPingsBothServer) error
	StreamPingsIn(PingReplyer_StreamPingsInServer) error
	StreamPingsOut(*PingMessage, PingReplyer_StreamPingsOutServer) error
	mustEmbedUnimplementedPingReplyerServer()
}

// UnimplementedPingReplyerServer must be embedded to have forward compatible implementations.
type UnimplementedPingReplyerServer struct {
}

func (UnimplementedPingReplyerServer) Ping(context.Context, *PingMessage) (*PingMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPingReplyerServer) StreamPingsBoth(PingReplyer_StreamPingsBothServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPingsBoth not implemented")
}
func (UnimplementedPingReplyerServer) StreamPingsIn(PingReplyer_StreamPingsInServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPingsIn not implemented")
}
func (UnimplementedPingReplyerServer) StreamPingsOut(*PingMessage, PingReplyer_StreamPingsOutServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPingsOut not implemented")
}
func (UnimplementedPingReplyerServer) mustEmbedUnimplementedPingReplyerServer() {}

// UnsafePingReplyerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingReplyerServer will
// result in compilation errors.
type UnsafePingReplyerServer interface {
	mustEmbedUnimplementedPingReplyerServer()
}

func RegisterPingReplyerServer(s grpc.ServiceRegistrar, srv PingReplyerServer) {
	s.RegisterService(&PingReplyer_ServiceDesc, srv)
}

func _PingReplyer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingReplyerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PingReplyer_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingReplyerServer).Ping(ctx, req.(*PingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingReplyer_StreamPingsBoth_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PingReplyerServer).StreamPingsBoth(&pingReplyerStreamPingsBothServer{stream})
}

type PingReplyer_StreamPingsBothServer interface {
	Send(*PingMessage) error
	Recv() (*PingMessage, error)
	grpc.ServerStream
}

type pingReplyerStreamPingsBothServer struct {
	grpc.ServerStream
}

func (x *pingReplyerStreamPingsBothServer) Send(m *PingMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pingReplyerStreamPingsBothServer) Recv() (*PingMessage, error) {
	m := new(PingMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PingReplyer_StreamPingsIn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PingReplyerServer).StreamPingsIn(&pingReplyerStreamPingsInServer{stream})
}

type PingReplyer_StreamPingsInServer interface {
	SendAndClose(*PingMessage) error
	Recv() (*PingMessage, error)
	grpc.ServerStream
}

type pingReplyerStreamPingsInServer struct {
	grpc.ServerStream
}

func (x *pingReplyerStreamPingsInServer) SendAndClose(m *PingMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pingReplyerStreamPingsInServer) Recv() (*PingMessage, error) {
	m := new(PingMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PingReplyer_StreamPingsOut_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PingMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PingReplyerServer).StreamPingsOut(m, &pingReplyerStreamPingsOutServer{stream})
}

type PingReplyer_StreamPingsOutServer interface {
	Send(*PingMessage) error
	grpc.ServerStream
}

type pingReplyerStreamPingsOutServer struct {
	grpc.ServerStream
}

func (x *pingReplyerStreamPingsOutServer) Send(m *PingMessage) error {
	return x.ServerStream.SendMsg(m)
}

// PingReplyer_ServiceDesc is the grpc.ServiceDesc for PingReplyer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingReplyer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PingReplyer",
	HandlerType: (*PingReplyerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PingReplyer_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPingsBoth",
			Handler:       _PingReplyer_StreamPingsBoth_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamPingsIn",
			Handler:       _PingReplyer_StreamPingsIn_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamPingsOut",
			Handler:       _PingReplyer_StreamPingsOut_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/api.proto",
}
